// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa8J1LLNB_a9Gv92_TgajgevVKtg3H020',
    appId: '1:92295095166:web:cdf5440de2b29dddaa092f',
    messagingSenderId: '92295095166',
    projectId: 'socialapp-1f55f',
    authDomain: 'socialapp-1f55f.firebaseapp.com',
    storageBucket: 'socialapp-1f55f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2_A2cqot3IQ-vZgL2x5A1A2OK3oVpMa8',
    appId: '1:92295095166:android:98bbd72307c7d166aa092f',
    messagingSenderId: '92295095166',
    projectId: 'socialapp-1f55f',
    storageBucket: 'socialapp-1f55f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi7dXD2CbVgzxbfg22usP4BfDsvoWQJWo',
    appId: '1:92295095166:ios:591e73ae11645a46aa092f',
    messagingSenderId: '92295095166',
    projectId: 'socialapp-1f55f',
    storageBucket: 'socialapp-1f55f.firebasestorage.app',
    iosBundleId: 'com.example.socialMedia',
  );
}
